name: lm_labs_generator
description: Some code generators used by LM Labs.
repository: https://github.com/glemartret/lm_labs_generator
issue_tracker: https://github.com/glemartret/lm_labs_generator/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
version: 0.0.2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  recase: ^4.1.0
  source_gen: ^2.0.0

dev_dependencies:
  lm_labs_flutter_lints: ^0.3.0

dependency_overrides:
  meta: ^1.15.0
