name: lm_labs_generator
description: Some code generators used by LM Labs.
repository: https://github.com/glemartret/lm_labs_generator
issue_tracker: https://github.com/glemartret/lm_labs_generator/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
version: 1.0.1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  analyzer: "^9.0.0"
  build: ">=2.0.0 <5.0.0"
  recase: ^4.1.0
  source_gen: ">=2.0.0 <5.0.0"

dev_dependencies:
  lm_labs_flutter_lints: ^1.0.0
